FROM mcr.microsoft.com/dotnet/sdk:7.0 as SDK 

FROM continuumio/miniconda3 as conda3


RUN ["apt" ,"update"]
RUN ["apt", "install", "-y", "protobuf-compiler"]
RUN ["apt", "install", "-y", "protobuf-compiler-grpc"]

WORKDIR /tools 

COPY . .

ENTRYPOINT [ "tail" ,"-f", "/dev/null" ] 
