FROM mcr.microsoft.com/dotnet/sdk:7.0 as SDK 

RUN ["apt" ,"update"]
RUN ["apt", "install", "-y", "protobuf-compiler"]
RUN ["apt", "install", "-y", "protobuf-compiler-grpc"]
RUN apt install -y  python3 python3-pip
RUN pip install kazoo  xlrd==1.2.0 argparse

WORKDIR /tools 

COPY . .

VOLUME ./src:./src

#ENTRYPOINT [ "tail" ,"-f", "/dev/null" ] 
ENTRYPOINT [ "sh" , "auto_gen_code.sh" ]
