// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: excelconst.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Proto {

  /// <summary>Holder for reflection information generated from excelconst.proto</summary>
  public static partial class ExcelconstReflection {

    #region Descriptor
    /// <summary>File descriptor for excelconst.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ExcelconstReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChBleGNlbGNvbnN0LnByb3RvEgVQcm90byoyCgtEZWZhbmNlVHlwZRIKCgZO",
            "b3JtYWwQABIKCgZTaGllbGQQARILCgdBcm1vcmVkEAIqPgoMSGVyb0NhdGVn",
            "b3J5EgwKCEhDX0ZvcmNlEAASEAoMSENfS25vd2xlZGdlEAESDgoKSENfQWdp",
            "bGl0eRACKjQKCkRhbWFnZVR5cGUSDQoJQ29uZnVzaW9uEAASDAoIUGh5c2lj",
            "YWwQARIJCgVNYWdpYxACKlEKD0xldmVsVW5sb2NrVHlwZRIICgROb25lEAAS",
            "FQoRTmVlZENvbXBsZXRlTGV2ZWwQARIMCghOZWVkSXRlbRACEg8KC0NvbnN1",
            "bWVJdGVtEAMqqgIKEEhlcm9Qcm9wZXJ0eVR5cGUSDAoISFBUX05vbmUQABIK",
            "CgZEYW1hZ2UQARILCgdEZWZhbmNlEAISCQoFTWF4SFAQAxIJCgVNYXhNUBAE",
            "EgcKA0NydBAFEgkKBURvZGdlEAYSEQoNQ3J0RGFtYWdlUmF0ZRAHEg0KCU1v",
            "dmVTcGVlZBAIEg8KC0F0dGFja1NwZWVkEAkSDQoJQ2FzdFNwZWVkEAoSCwoH",
            "SGl0QmFjaxALEgwKCEhpdEltbW9iEAwSCwoHSGl0QnVybhANEg0KCUhpdEZy",
            "ZWV6ZRAOEgsKB0hQRHJhaW4QDxILCgdNcERyYWluEBASCgoGVnNCb3NzEBES",
            "CwoHVnNFbGl0ZRASEgcKA0hpdBATEhAKDFZpZXdEaXN0YW5jZRAUKmMKDkFj",
            "dGlvbkxvY2tUeXBlEgwKCEFMVF9Ob25lEAASDAoITk9fU0tJTEwQARILCgdO",
            "T19NT1ZFEAISDQoJTk9fQVRUQUNLEAQSDgoKTk9fSU5ISURFThAIEgkKBU5P",
            "X0FpEBAqUwoISXRlbVR5cGUSCwoHSVRfTm9uZRAAEg0KCUlUX0hQSXRlbRAB",
            "Eg0KCUlUX01QSXRlbRACEgwKCElUX0VxdWlwEAMSDgoKSVRfQ29uc3VtZRAE",
            "KlgKEE1hZ2ljUmVsZWFzZVR5cGUSDAoITVJUX05PTkUQABIUChBNUlRfTm9y",
            "bWFsQXR0YWNrEAESEQoNTVJUX0Jvcm5NYWdpYxACEg0KCU1SVF9NYWdpYxAD",
            "KmwKFE1hZ2ljUmVsZWFzZUFJVGFyZ2V0EgsKB01BVF9BTEwQABINCglNQVRf",
            "RW5lbXkQARIPCgtNQVRfT3duVGVhbRACEhoKFk1BVF9Pd25UZWFtV2l0aE91",
            "dFNlbGYQAxILCgdNQVRfT3duEAQqQwoNRXF1aXBtZW50VHlwZRILCgdFVF9O",
            "b25lEAASBwoDQXJtEAESCAoEQm9keRACEggKBEhlYWQQAxIICgRGb290EAQq",
            "jwEKDEdldFZhbHVlRnJvbRIRCg1DdXJyZW50Q29uZmlnEAASFAoQTWFnaWNM",
            "ZXZlbFBhcmFtMRABEhQKEE1hZ2ljTGV2ZWxQYXJhbTIQAhIUChBNYWdpY0xl",
            "dmVsUGFyYW0zEAMSFAoQTWFnaWNMZXZlbFBhcmFtNBAEEhQKEE1hZ2ljTGV2",
            "ZWxQYXJhbTUQBSpSCg5UYXJnZXRUZWFtVHlwZRIHCgNBTEwQABIJCgVFbmVt",
            "eRABEgsKB093blRlYW0QAhIWChJPd25UZWFtV2l0aE91dFNlbGYQAxIHCgNP",
            "d24QBCo2CglTdGFuZFR5cGUSCwoHU1RfTk9ORRAAEg0KCVNUX1JhbmRvbRAB",
            "Eg0KCVNUX0Fyb3VuZBACKigKB01hcFR5cGUSCwoHTVRfTm9uZRAAEggKBEJv",
            "c3MQARIGCgJQSxACKmYKE01hcExldmVsRWxlbWVudFR5cGUSDQoJTUxFVF9O",
            "T05FEAASEgoOTUxFVF9UcmFuc3BvcnQQARIZChVNTEVUX0Ryb3BHcm91cEVs",
            "ZW1lbnQQAhIRCg1NTEVUX0NoZXN0Qm94EANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Proto.DefanceType), typeof(global::Proto.HeroCategory), typeof(global::Proto.DamageType), typeof(global::Proto.LevelUnlockType), typeof(global::Proto.HeroPropertyType), typeof(global::Proto.ActionLockType), typeof(global::Proto.ItemType), typeof(global::Proto.MagicReleaseType), typeof(global::Proto.MagicReleaseAITarget), typeof(global::Proto.EquipmentType), typeof(global::Proto.GetValueFrom), typeof(global::Proto.TargetTeamType), typeof(global::Proto.StandType), typeof(global::Proto.MapType), typeof(global::Proto.MapLevelElementType), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  ///防御类型
  /// </summary>
  public enum DefanceType {
    /// <summary>
    ///普通
    /// </summary>
    [pbr::OriginalName("Normal")] Normal = 0,
    /// <summary>
    ///盾牌
    /// </summary>
    [pbr::OriginalName("Shield")] Shield = 1,
    /// <summary>
    ///重甲
    /// </summary>
    [pbr::OriginalName("Armored")] Armored = 2,
  }

  /// <summary>
  ///种族类型
  /// </summary>
  public enum HeroCategory {
    /// <summary>
    ///力量
    /// </summary>
    [pbr::OriginalName("HC_Force")] HcForce = 0,
    /// <summary>
    ///智力
    /// </summary>
    [pbr::OriginalName("HC_Knowledge")] HcKnowledge = 1,
    /// <summary>
    ///敏捷
    /// </summary>
    [pbr::OriginalName("HC_Agility")] HcAgility = 2,
  }

  /// <summary>
  ///伤害类型
  /// </summary>
  public enum DamageType {
    /// <summary>
    ///混乱
    /// </summary>
    [pbr::OriginalName("Confusion")] Confusion = 0,
    /// <summary>
    ///物理
    /// </summary>
    [pbr::OriginalName("Physical")] Physical = 1,
    /// <summary>
    ///魔法
    /// </summary>
    [pbr::OriginalName("Magic")] Magic = 2,
  }

  /// <summary>
  ///解锁条件
  /// </summary>
  public enum LevelUnlockType {
    /// <summary>
    ///无需解锁
    /// </summary>
    [pbr::OriginalName("None")] None = 0,
    /// <summary>
    ///前置关卡
    /// </summary>
    [pbr::OriginalName("NeedCompleteLevel")] NeedCompleteLevel = 1,
    /// <summary>
    ///需求道具
    /// </summary>
    [pbr::OriginalName("NeedItem")] NeedItem = 2,
    /// <summary>
    ///消耗道具
    /// </summary>
    [pbr::OriginalName("ConsumeItem")] ConsumeItem = 3,
  }

  /// <summary>
  ///属性枚举
  /// </summary>
  public enum HeroPropertyType {
    [pbr::OriginalName("HPT_None")] HptNone = 0,
    /// <summary>
    ///伤害
    /// </summary>
    [pbr::OriginalName("Damage")] Damage = 1,
    /// <summary>
    ///防御
    /// </summary>
    [pbr::OriginalName("Defance")] Defance = 2,
    /// <summary>
    ///HP
    /// </summary>
    [pbr::OriginalName("MaxHP")] MaxHp = 3,
    /// <summary>
    ///魔法上限
    /// </summary>
    [pbr::OriginalName("MaxMP")] MaxMp = 4,
    /// <summary>
    ///暴击率
    /// </summary>
    [pbr::OriginalName("Crt")] Crt = 5,
    /// <summary>
    ///闪避 dodge
    /// </summary>
    [pbr::OriginalName("Dodge")] Dodge = 6,
    /// <summary>
    ///暴击伤害倍数 万分比
    /// </summary>
    [pbr::OriginalName("CrtDamageRate")] CrtDamageRate = 7,
    /// <summary>
    ///移动速度 cm/s
    /// </summary>
    [pbr::OriginalName("MoveSpeed")] MoveSpeed = 8,
    /// <summary>
    ///攻击速度 次数秒 * 1000 
    /// </summary>
    [pbr::OriginalName("AttackSpeed")] AttackSpeed = 9,
    /// <summary>
    ///释法速度 毫秒
    /// </summary>
    [pbr::OriginalName("CastSpeed")] CastSpeed = 10,
    /// <summary>
    ///攻击击退  cm
    /// </summary>
    [pbr::OriginalName("HitBack")] HitBack = 11,
    /// <summary>
    ///攻击硬直 毫秒
    /// </summary>
    [pbr::OriginalName("HitImmob")] HitImmob = 12,
    /// <summary>
    ///攻击燃烧
    /// </summary>
    [pbr::OriginalName("HitBurn")] HitBurn = 13,
    /// <summary>
    ///攻击冰冻
    /// </summary>
    [pbr::OriginalName("HitFreeze")] HitFreeze = 14,
    /// <summary>
    ///吸血等级  万分比
    /// </summary>
    [pbr::OriginalName("HPDrain")] Hpdrain = 15,
    /// <summary>
    ///MP 吸取等级 万分比
    /// </summary>
    [pbr::OriginalName("MpDrain")] MpDrain = 16,
    /// <summary>
    ///boss 伤害加成 万分比
    /// </summary>
    [pbr::OriginalName("VsBoss")] VsBoss = 17,
    /// <summary>
    ///精英 伤害加成 万分比
    /// </summary>
    [pbr::OriginalName("VsElite")] VsElite = 18,
    /// <summary>
    ///命中
    /// </summary>
    [pbr::OriginalName("Hit")] Hit = 19,
    /// <summary>
    ///视野范围
    /// </summary>
    [pbr::OriginalName("ViewDistance")] ViewDistance = 20,
  }

  /// <summary>
  ///行为锁
  /// </summary>
  public enum ActionLockType {
    [pbr::OriginalName("ALT_None")] AltNone = 0,
    /// <summary>
    ///禁止释放主动技能
    /// </summary>
    [pbr::OriginalName("NO_SKILL")] NoSkill = 1,
    /// <summary>
    ///禁止移动
    /// </summary>
    [pbr::OriginalName("NO_MOVE")] NoMove = 2,
    /// <summary>
    ///禁止攻击
    /// </summary>
    [pbr::OriginalName("NO_ATTACK")] NoAttack = 4,
    /// <summary>
    ///隐形 invisible
    /// </summary>
    [pbr::OriginalName("NO_INHIDEN")] NoInhiden = 8,
    /// <summary>
    ///无ai
    /// </summary>
    [pbr::OriginalName("NO_Ai")] NoAi = 16,
  }

  public enum ItemType {
    [pbr::OriginalName("IT_None")] ItNone = 0,
    /// <summary>
    ///hp
    /// </summary>
    [pbr::OriginalName("IT_HPItem")] ItHpitem = 1,
    [pbr::OriginalName("IT_MPItem")] ItMpitem = 2,
    /// <summary>
    ///装备
    /// </summary>
    [pbr::OriginalName("IT_Equip")] ItEquip = 3,
    /// <summary>
    ///消耗类道具 本身没有任何功能其他系统定义
    /// </summary>
    [pbr::OriginalName("IT_Consume")] ItConsume = 4,
  }

  public enum MagicReleaseType {
    [pbr::OriginalName("MRT_NONE")] MrtNone = 0,
    /// <summary>
    ///普通攻击
    /// </summary>
    [pbr::OriginalName("MRT_NormalAttack")] MrtNormalAttack = 1,
    /// <summary>
    ///出生技能
    /// </summary>
    [pbr::OriginalName("MRT_BornMagic")] MrtBornMagic = 2,
    /// <summary>
    ///魔法
    /// </summary>
    [pbr::OriginalName("MRT_Magic")] MrtMagic = 3,
  }

  public enum MagicReleaseAITarget {
    /// <summary>
    ///所有
    /// </summary>
    [pbr::OriginalName("MAT_ALL")] MatAll = 0,
    /// <summary>
    ///敌人
    /// </summary>
    [pbr::OriginalName("MAT_Enemy")] MatEnemy = 1,
    /// <summary>
    ///自己队友
    /// </summary>
    [pbr::OriginalName("MAT_OwnTeam")] MatOwnTeam = 2,
    /// <summary>
    ///不包含自己
    /// </summary>
    [pbr::OriginalName("MAT_OwnTeamWithOutSelf")] MatOwnTeamWithOutSelf = 3,
    /// <summary>
    ///只有自己
    /// </summary>
    [pbr::OriginalName("MAT_Own")] MatOwn = 4,
  }

  public enum EquipmentType {
    [pbr::OriginalName("ET_None")] EtNone = 0,
    /// <summary>
    ///手
    /// </summary>
    [pbr::OriginalName("Arm")] Arm = 1,
    /// <summary>
    ///衣服护驾
    /// </summary>
    [pbr::OriginalName("Body")] Body = 2,
    /// <summary>
    ///头
    /// </summary>
    [pbr::OriginalName("Head")] Head = 3,
    /// <summary>
    ///脚
    /// </summary>
    [pbr::OriginalName("Foot")] Foot = 4,
  }

  public enum GetValueFrom {
    /// <summary>
    ///获取当前配置值
    /// </summary>
    [pbr::OriginalName("CurrentConfig")] CurrentConfig = 0,
    /// <summary>
    ///取魔法等级表数据参数1
    /// </summary>
    [pbr::OriginalName("MagicLevelParam1")] MagicLevelParam1 = 1,
    /// <summary>
    ///参数2
    /// </summary>
    [pbr::OriginalName("MagicLevelParam2")] MagicLevelParam2 = 2,
    /// <summary>
    ///参数3
    /// </summary>
    [pbr::OriginalName("MagicLevelParam3")] MagicLevelParam3 = 3,
    /// <summary>
    ///参数4
    /// </summary>
    [pbr::OriginalName("MagicLevelParam4")] MagicLevelParam4 = 4,
    /// <summary>
    ///参数5
    /// </summary>
    [pbr::OriginalName("MagicLevelParam5")] MagicLevelParam5 = 5,
  }

  public enum TargetTeamType {
    /// <summary>
    ///所有
    /// </summary>
    [pbr::OriginalName("ALL")] All = 0,
    /// <summary>
    ///敌人
    /// </summary>
    [pbr::OriginalName("Enemy")] Enemy = 1,
    /// <summary>
    ///自己队友
    /// </summary>
    [pbr::OriginalName("OwnTeam")] OwnTeam = 2,
    /// <summary>
    ///不包含自己
    /// </summary>
    [pbr::OriginalName("OwnTeamWithOutSelf")] OwnTeamWithOutSelf = 3,
    /// <summary>
    ///只有自己
    /// </summary>
    [pbr::OriginalName("Own")] Own = 4,
  }

  public enum StandType {
    [pbr::OriginalName("ST_NONE")] StNone = 0,
    /// <summary>
    ///随机
    /// </summary>
    [pbr::OriginalName("ST_Random")] StRandom = 1,
    /// <summary>
    ///围绕
    /// </summary>
    [pbr::OriginalName("ST_Around")] StAround = 2,
  }

  public enum MapType {
    [pbr::OriginalName("MT_None")] MtNone = 0,
    /// <summary>
    ///boss挑战
    /// </summary>
    [pbr::OriginalName("Boss")] Boss = 1,
    /// <summary>
    ///玩家挑战
    /// </summary>
    [pbr::OriginalName("PK")] Pk = 2,
  }

  public enum MapLevelElementType {
    [pbr::OriginalName("MLET_NONE")] MletNone = 0,
    /// <summary>
    ///传送点
    /// </summary>
    [pbr::OriginalName("MLET_Transport")] MletTransport = 1,
    /// <summary>
    ///掉落组物体
    /// </summary>
    [pbr::OriginalName("MLET_DropGroupElement")] MletDropGroupElement = 2,
    /// <summary>
    ///宝箱
    /// </summary>
    [pbr::OriginalName("MLET_ChestBox")] MletChestBox = 3,
  }

  #endregion

}

#endregion Designer generated code
