// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: notify_server.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Proto {
  public static partial class NotifyServices
  {
    static readonly string __ServiceName = "Proto.NotifyServices";

    static readonly grpc::Marshaller<global::Proto.S2N_RouteSendNotify> __Marshaller_Proto_S2N_RouteSendNotify = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.S2N_RouteSendNotify.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Proto.N2S_RouteSendNotify> __Marshaller_Proto_N2S_RouteSendNotify = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.N2S_RouteSendNotify.Parser.ParseFrom);

    static readonly grpc::Method<global::Proto.S2N_RouteSendNotify, global::Proto.N2S_RouteSendNotify> __Method_RouteSendNotify = new grpc::Method<global::Proto.S2N_RouteSendNotify, global::Proto.N2S_RouteSendNotify>(
        grpc::MethodType.Unary,
        __ServiceName,
        "RouteSendNotify",
        __Marshaller_Proto_S2N_RouteSendNotify,
        __Marshaller_Proto_N2S_RouteSendNotify);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Proto.NotifyServerReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of NotifyServices</summary>
    [grpc::BindServiceMethod(typeof(NotifyServices), "BindService")]
    public abstract partial class NotifyServicesBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Proto.N2S_RouteSendNotify> RouteSendNotify(global::Proto.S2N_RouteSendNotify request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for NotifyServices</summary>
    public partial class NotifyServicesClient : grpc::ClientBase<NotifyServicesClient>
    {
      /// <summary>Creates a new client for NotifyServices</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public NotifyServicesClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for NotifyServices that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public NotifyServicesClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected NotifyServicesClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected NotifyServicesClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Proto.N2S_RouteSendNotify RouteSendNotify(global::Proto.S2N_RouteSendNotify request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RouteSendNotify(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Proto.N2S_RouteSendNotify RouteSendNotify(global::Proto.S2N_RouteSendNotify request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_RouteSendNotify, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.N2S_RouteSendNotify> RouteSendNotifyAsync(global::Proto.S2N_RouteSendNotify request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return RouteSendNotifyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.N2S_RouteSendNotify> RouteSendNotifyAsync(global::Proto.S2N_RouteSendNotify request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_RouteSendNotify, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override NotifyServicesClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new NotifyServicesClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(NotifyServicesBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_RouteSendNotify, serviceImpl.RouteSendNotify).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the  service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, NotifyServicesBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_RouteSendNotify, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Proto.S2N_RouteSendNotify, global::Proto.N2S_RouteSendNotify>(serviceImpl.RouteSendNotify));
    }

  }
}
#endregion
