version: '3'

services: 
    login:
        image: 'game/login:latest'
        ports: 
            - '3000:3000'
            - '1100:1100'
        environment: 
            - DBHOST=$MONGOURL
            - MAP_LOGIN_SERVICE_PORT=1100
            - SERVICE_HOST=${ADDRESS}
            - HOST_NAME=${ADDRESS}
            - ZK_SERVER_LIST=${ZK}
            - KFK_SERVER_LIST=${KAFKA}
            - MAP_LOGIN_PORT=3000
    gate:
        image: 'game/gate:latest'
        ports:
            - '2000:2000'
            - '1700:1700'
        environment:
            - DBHOST=$MONGOURL
            - DB_GATE=gate1
            - SERVERGROUPID=1
            - MAXPLAYER=10000
            - SERVICE_HOST=${ADDRESS}
            - HOST_NAME=${ADDRESS}
            - ZK_SERVER_LIST=${ZK}
            - KFK_SERVER_LIST=${KAFKA}
            - MAP_GATE_PORT=2000
            - MAP_GATE_SERVICE_PORT=1700
    notify:
        image: 'game/notify:latest'
        ports: 
            - '1300:1300'
        environment: 
            - DBHOST=$MONGOURL
            - DB_CHAT=chat
            - SERVICE_HOST=${ADDRESS}
            - HOST_NAME=${ADDRESS}
            - ZK_SERVER_LIST=${ZK}
            - KFK_SERVER_LIST=${KAFKA}
            - MAP_NOTIFY_SERVICE_PORT=1300
    chat:
        image: 'game/chat:latest'
        ports:  
            - '2200:2200'
            - '1600:1600'
        environment: 
            - DBHOST=$MONGOURL
            - DB_CHAT=chat
            - MAX_PLAYER=4000
            - SERVERID=1000
            - SERVICE_HOST=${ADDRESS}
            - HOST_NAME=${ADDRESS}
            - ZK_SERVER_LIST=${ZK}
            - KFK_SERVER_LIST=${KAFKA}
            - MAP_CHAT_PORT=2200
            - MAP_CHAT_SERVICE_PORT=1600
        depends_on: 
            - notify           
    match:
        image: 'game/match:latest'
        ports: 
            - '1500:1500'
        environment: 
            - DBHOST=$MONGOURL
            - DB_MATCH=match
            - SERVICE_HOST=${ADDRESS} 
            - HOST_NAME=${ADDRESS}
            - ZK_SERVER_LIST=${ZK}
            - KFK_SERVER_LIST=${KAFKA}
            - MAP_MATCH_SERVICE_PORT=1500


