name: Build Server Images

on:
  push:
    #branches: [ "release/**" ]
    paths:
      - 'Server/**'

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
    - uses: actions/checkout@v3
    - name: build Server
      run: mkdir serverout && sh buildforci.sh ${{github.run_number}} `pwd`/serverout


    
