name: Build Server Images

on:
  push:
    #branches: [ "release/**" ]
    paths:
      - 'Server/**'

jobs:

  build:

    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:

    - name: build Server
      uses: actions/checkout@v3
      run: mkdir serverout && sh buildforci.sh version-${{github.run_number}} `pwd`/serverout

    - name: jenkins Request Rebuild Server  
      uses: Satak/webrequest-action@v1.2.3
      with: 
       url: http://andew25a.synology.me:2080/generic-webhook-trigger/invoke?token=andrew_auto_build
       method: GET

    
