name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build Excel And Proto
      run:  cd PublicTools && sh runbuild.sh
    - name: push
      uses: actions-x/commit@v6
      with:
        email: andrew-auto@github.com
        name: GitHub Actions Autocommitter
        branch: master-ci

    
